[profile.default]
solc_version = "0.8.17"
script = 'script'
test = 'test'
extra_output = ['storageLayout']
evm_version = "london"
fs_permissions=[
  {access="read", path="./out"},
  {access="read", path= "./script/config" },
  {access="read", path= "./sphinx.lock" },
  {access="read-write", path="./cache"},
]
allow_paths = ["../.."]
auto_detect_remappings = false
libs = ["lib"]

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
polygon-pos = "https://polygon-rpc.com"
optimistic = "https://rpc.ankr.com/optimism"
arbitrum = "https://arb1.arbitrum.io/rpc"
linea = "https://rpc.linea.build"
ethereum = "https://rpc.ankr.com/eth"
blast = "https://rpc.blast.io"
polygon-zkevm = "https://zkevm-rpc.com"
darwinia = "https://darwinia-rpc.itering.io"
bsc = "https://rpc.ankr.com/bsc"
base = "https://mainnet.base.org"
gnosis = "https://rpc.gnosischain.com"
mantle = "https://rpc.mantle.xyz"
scroll = "https://rpc.scroll.io"
moonbeam = "https://rpc.api.moonbeam.network"
astar-zkevm = "https://rpc.startale.com/astar-zkevm"
crab = "https://crab-rpc.itering.io"
