[base]
name = "base"
chainId = 8453
deployer = "0x80D4c766C5142D1313D531Afe7384D0D5E108Db3"
bridgev3 = "0xbA5D580B18b6436411562981e02c8A9aA1776D10"

[messager]
[messager.messagers]
types = ["layerzero"]

[messager.layerzero]
id = 184
messager = "0x61B6B8c7C00aA7F060a2BEDeE6b11927CC9c3eF1"

[token]
[token.symbols]
symbols = ["usdc"]

[token.usdc]
address = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
decimals = 6
protocolFee = 100000
