[base]
name = "mantle"
chainId = 5000
deployer = "0x80D4c766C5142D1313D531Afe7384D0D5E108Db3"
bridgev3 = "0xbA5D580B18b6436411562981e02c8A9aA1776D10"

[messager]
[messager.messagers]
types = ["layerzero"]

[messager.layerzero]
id = 181
messager = "0x61B6B8c7C00aA7F060a2BEDeE6b11927CC9c3eF1"

[token]
[token.symbols]
symbols = ["usdt", "usdc"]

[token.usdt]
address = "0x201EBa5CC46D216Ce6DC03F6a759e8E766e956aE"
decimals = 6

[token.usdc]
address = "0x09Bc4E0D864854c6aFB6eB9A9cdF58aC190D0dF9"
decimals = 6
